(function(){var e=10,f=function(){if(!document.head&&0<--e)window.setTimeout(f,100);else{var h=document.createElement("meta");h.httpEquiv="Content-Security-Policy";h.content="script-src 'self' https://ssl.google-analytics.com; object-src 'self';";document.getElementsByTagName("head")[0].appendChild(h)}};f()})();
(function(e){var f=safari.extension&&safari.extension.globalPage&&safari.extension.globalPage.contentWindow===window;e.extend({internal:{window:{get:function(){var b,a;if((b=safari.application)&&(a=b.activeBrowserWindow||b.browserWindows[0])||(b=safari.self)&&(a=b.browserWindow)||(b=safari.application)&&(a=b.openBrowserWindow()))return a}},tabs:function(){var b={},a=0,c={register:function(c){var g=++a;b[g]={id:g,page:c};return g},unregister:function(a){(a=c.getByPage(a))&&b.delete(a.id)},getById:function(c){return b[c]},
getAll:function(){var c=[],a;for(a in b)b.hasOwnProperty(a)&&c.push(b[a]);return c},getByPage:function(c){for(var a in b)if(b.hasOwnProperty(a)&&b[a].page===c)return b[a]},getByPageEx:function(a){var b=c.getByPage(a);b||(a=c.register(a),b=c.getById(a));return b}};return c}()}});e.extend({extension:function(){var b;if(f){var a=[];e.internal.listeners.register("connect",function(c){var b=c.message.response_id,g=[],k=[],n=e.internal&&e.internal.tabs?e.internal.tabs.getByPageEx(c.target.page).id:null;
a.forEach(function(a){var f={postMessage:function(a){var g=c.target.page;g&&g.dispatchMessage("connect.postMessage",{response_id:b,data:a||{},sender:{url:window.location.href}})},onMessage:{addListener:function(c){g.push(c)}},onDisconnect:{addListener:function(c){k&&k.push(c)}},disconnect:function(){var a=c.target.page;a&&a.dispatchMessage("connect.postMessage",{response_id:b});f=k=g=null},sender:{tab:{page:c.target.page,id:n,url:c.target.url||""},url:null}};e.internal.responses.register(function(c,
a){f&&(c?(f.sender.url=a.url,g.forEach(function(a){a(c)})):(k.forEach(function(c){c()}),e.internal.responses.delete(b),f=null))},b);a(f)})});e.internal.listeners.register("document.beforeload",function(c){c.target.page&&!e.internal.tabs.getByPage(c.target.page)&&e.internal.tabs.register(c.target.page)});b={onConnect:{addListener:function(c){a.push(c)}},onConnectExternal:{addListener:function(c){}},onMessageExternal:{addListener:function(c){}},manifest:function(){var c={};c.__defineGetter__("version",
function(){return safari&&safari.extension&&(safari.extension.displayVersion||(safari.extension.displayVersion=e.internal.info.read("CFBundleShortVersionString","string"),safari.extension.bundleVersion=e.internal.info.read("CFBundleVersion","string")),safari.extension.displayVersion)?[safari.extension.displayVersion,safari.extension.bundleVersion].filter(function(c){return c}).join("."):"?"});return c}(),getViews:function(c){if(c.popup)return safari.extension.popovers},isAllowedFileSchemeAccess:function(c){c(!1)}}}else b=
{};b.urls={prepareForReport:function(c){return c&&c.replace?c.replace(new RegExp(/(.+:\/\/[^\/]+\/)([^\/]*\/)(.+$)/),"$1$3"):c}};b.__defineGetter__("inIncognitoContext",function(){var c;if(!(c=!(!safari.privateBrowsing||!safari.privateBrowsing.enabled))){var a;c=window.localStorage;try{c.setItem("test","test");var b=c.getItem("test");c.removeItem("test");a="test"===b}catch(k){a=!1}c=!a}return c});return b}(),runtime:function(){if(f)return{onInstalled:{addListener:function(b){}},onUpdateAvailable:{addListener:function(b){}}}}(),
tabs:function(){return f?{onActivated:{addListener:function(b){}},onUpdated:function(){if(f){var b=[];(safari.application||safari.self).addEventListener("navigate",function(a){if(a.target&&a.target.url){var c=e.internal.tabs.getByPageEx(a.target.page).id,d={status:"complete"},g={url:a.target.url,id:c};b.forEach(function(a){a(c,d,g)})}},!0);return{addListener:function(a){b.push(a)}}}}(),onReplaced:function(){if(f){var b=[];(safari.application||safari.self).addEventListener("document.replaced",function(a){var c=
e.internal.tabs.getByPageEx(a.target.page);c.prerendered=!1;b.forEach(function(a){a(c.id,-1)});e.browserAction.update(c)},!0);return{addListener:function(a){b.push(a)}}}}(),onRemoved:function(){if(f){var b=[];(safari.application||safari.self).addEventListener("close",function(a){if(a.target instanceof SafariBrowserTab){var c=e.internal.tabs.getByPageEx(a.target.page).id,d={};b.forEach(function(a){a(c,d)});e.internal.tabs.unregister(a.target)}},!0);return{addListener:function(a){b.push(a)}}}}(),executeScript:function(b,
a,c){c&&c()},create:function(b,a){var c;if(c=e.internal.window.get()){c=c.openTab();var d=e.internal.tabs.getByPageEx(c.page).id;c.url=b.url;c.id=d;c.activate();a&&a(c)}else console.warn("rea: unable to retrieve a browser window for tab creation")},update:function(b,a,c){var d=e.internal.tabs.getById(b);if(d){if(a.url&&d.page.dispatchMessage("internal.loadurl",a),a.active){var g;a:{if(safari.application.browserWindows)for(b=0;b<safari.application.browserWindows.length;b++)if((a=safari.application.browserWindows[b])&&
a.tabs)for(var k=0;k<a.tabs.length;k++)if(a.tabs[k].page===d.page){d=a.tabs[k];break a}d=void 0}(g=d)&&g.activate()}}else console.warn("rea.tabs.update: unable to send message to unknown tab"+b);c&&c()},remove:function(b,a){var c=e.internal.tabs.getById(b);c?c.page.close?c.page.close():c.page.dispatchMessage("internal.close",{}):console.warn("rea.tabs.remove: unable to send message to unknown tab"+b);a&&a()},highlight:function(b,a){a&&a()},getSelected:function(b,a){var c;if(c=e.internal.window.get()){c=
c.activeTab;var d=e.internal.tabs.getByPageEx(c.page).id;a({url:c.url,id:d})}else console.warn("rea: unable to retrieve a browser window to determine the active tab")},get:function(b,a){var c=e.internal.tabs.getById(b),d;c&&(d={url:c.url,id:b});a(d)},query:function(b,a){if("normal"===b.windowType){var c=[];e.internal.tabs.getAll().forEach(function(a){c.push({id:a.id,url:a.url})});a(c)}else a([])},sendMessage:function(b,a,c,d){void 0===d&&(d=c);(c=e.internal.tabs.getById(b))?(b={response_id:e.internal.responses.register(d),
data:a},c.page.dispatchMessage("onMessage",b)):console.warn("rea.tabs.sendMessage: unable to send message to unknown tab"+b);d&&d()}}:{getSelected:function(b,a){return safari.extension.globalPage.contentWindow.rea.tabs.getSelected.apply(this,arguments)},query:function(b,a){return safari.extension.globalPage.contentWindow.rea.tabs.query.apply(this,arguments)},sendMessage:function(b,a,c,d){return safari.extension.globalPage.contentWindow.rea.tabs.sendMessage.apply(this,arguments)}}}(),webRequest:function(){if(f)return{headerModificationSupported:!1,
onBeforeRequest:function(){var b=[];(safari.application||safari.self).addEventListener("beforeNavigate",function(a){var c=e.internal.tabs.getByPageEx(a.target.page).id;if(a.url){var d={tabId:c,method:"GET",frameId:0,type:"main_frame",url:a.url},g;b.forEach(function(a){(a=a(d))&&a.redirectUrl&&(g=a.redirectUrl)});g&&(a.preventDefault(),(a=a.target.page)&&a.dispatchMessage("internal.loadurl",{url:g}))}},!0);return{addListener:function(a,c){b.push(a)},removeListener:function(a){a=b.indexOf(a);0<=a&&
b.splice(a,1)}}}(),onBeforeSendHeaders:{addListener:function(b,a){},removeListener:function(b){}},onHeadersReceived:function(){var b=[];e.internal.listeners.register("document.content_script",function(a){var c,d;if((d=a.target.page)&&(c=e.internal.tabs.getByPage(d))){a.message.top&&(c.prerendered=a.message.prerendered);var g={tabId:c.id,method:"GET",frameId:a.message.frameId,url:a.message.url,type:a.message.frameId?"sub_frame":"main_frame",requestId:null,responseHeaders:[]};b.forEach(function(a){a(g)})}else console.warn("rea.background.webRequest.onHeadersReceived: unable to find tab",
a.target,a.message)},!0);return{addListener:function(a,c){b.push(a)},removeListener:function(a){a=b.indexOf(a);0<=a&&b.splice(a,1)}}}(),onBeforeRedirect:{addListener:function(){},removeListener:function(){}},onResponseStarted:{addListener:function(){},removeListener:function(){}},onErrorOccurred:function(){var b=[];(safari.application||safari.self).addEventListener("navigate",function(a){if(!("Failed to open page"!==a.target.title||a.target.reader&&a.target.reader.available)){var c,d;if((d=a.target.page)&&
(c=e.internal.tabs.getByPage(d))){var g={tabId:c.id,frameId:0,url:a.target.url,type:"main_frame",requestId:null,error:"ERR_NAME_NOT_RESOLVED"};b.forEach(function(a){a(g)})}else console.warn("rea.background.webRequest.onErrorOccurred: unable to find tab",a.target)}});return{addListener:function(a,c){c&&c.types&&-1!=c.types.indexOf("main_frame")&&b.push(a)},removeListener:function(a){a=b.indexOf(a);0<=a&&b.splice(a,1)}}}(),handlerBehaviorChanged:function(b){}}}(),webNavigation:function(){return f?{supported:!1,
onCommitted:{addListener:function(b){}},onErrorOccurred:{addListener:function(b){}}}:{}}(),browserAction:function(){if(f){["activate","validate"].forEach(function(c){safari.application.addEventListener(c,function(c){c.target instanceof SafariBrowserTab&&(c=e.internal.tabs.getByPageEx(c.target.page),a(c))},!0)});var b=function(a){for(var c=0;c<safari.extension.toolbarItems.length;c++){var b=safari.extension.toolbarItems[c];if(b&&b.browserWindow&&b.browserWindow.tabs)for(var d=0;d<b.browserWindow.tabs.length;d++)if(b.browserWindow.tabs[d].page===
a)return b}},a=function(a){d.setIcon({tabId:a.id,path:a.path});d.setTitle({tabId:a.id,title:a.title+a.id});d.setBadgeText({tabId:a.id,text:a.badge||""})},c=function(a,c){return a&&a.activeTab&&a.activeTab.page===c},d={update:a,setIcon:function(a,d){var f,m;if(a.tabId&&(f=e.internal.tabs.getById(a.tabId))&&(m=b(f.page))){var h=c(m.browserWindow,f.page),l=a.path||e.extension.getURL(e.internal.info.read("Image","string"));f.icon=l;h&&(m.image=l)}d&&d()},setTitle:function(a){var d,f;if(a.tabId&&(d=e.internal.tabs.getById(a.tabId))&&
(f=b(d.page))){var h=c(f.browserWindow,d.page);a=a.title||e.internal.info.read("Label","string");d.title=a;h&&(f.label=a)}},setBadgeText:function(a){var d,f;a.tabId&&(d=e.internal.tabs.getById(a.tabId))&&(f=b(d.page))&&(a=parseInt(a.text)||0,d.badge=a,c(f.browserWindow,d.page)&&(f.badge=a))},setBadgeBackgroundColor:function(a){},setPopup:function(a){}};return d}}(),storage:function(){if(!f)return{local:{},sync:{}};var b=[];safari.extension.settings.addEventListener("change",function(a){var d={};d[a.key]=
{newValue:a.newValue,oldValue:a.oldValue};b.forEach(function(a){a(d,"local")})},!1);var a=function(a,b){if(a instanceof Array)for(var g=0;g<a.length;g++)b(a[g]);else if(a instanceof Object)for(g in a)a.hasOwnProperty(g)&&b(g);else b(a)};return{onChanged:{addListener:function(a){b.push(a)}},local:{set:function(a,b){for(var g in a)a.hasOwnProperty(g)&&safari.extension.settings.setItem(g,a[g]);b&&b()},get:function(c,b){var g={};if(null===c||void 0===c){c=[];var e=safari.extension.settings,f;for(f in e)e.hasOwnProperty(f)&&
c.push(f)}a(c,function(a){g[a]=safari.extension.settings.getItem(a)});b(g)},remove:function(b,d){a(b,function(a){safari.extension.settings.removeItem(a)});d&&d()},clear:function(a){safari.extension.settings.clear();a&&a()}},sync:{supported:!1,set:function(a,b){},get:function(a,b){},remove:function(a,b){},clear:function(a){}}}}(),syncFileSystem:function(){return f?{onFileStatusChanged:{addListener:function(b){}},onServiceStatusChanged:{addListener:function(b){}},supported:!1}:{}}(),contentSettings:function(){if(f)return{javascript:{set:function(b,
a){},get:function(b,a){},clear:function(b,a){}}}}(),downloads:function(){return f?{supported:!1,onChanged:{addListener:function(b){}},download:function(b,a){}}:{}}(),cookies:function(){if(f)return{getAll:function(b,a){a&&a([])}}}(),commands:function(){if(f)return{onCommand:{addListener:function(b){}}}}(),management:function(){if(f)return{getAll:function(b){b&&b([])},setEnabled:function(b,a,c){},uninstall:function(b,a,c){}}}(),notifications:function(){return f?{onPermissionLevelChanged:{addListener:function(b){}},
onClicked:{addListener:function(b){}},onClosed:{addListener:function(b){}},supported:!1,getPermissionLevel:function(b){},create:function(b,a,c){},clear:function(b,a){}}:{}}(),contextMenus:{supported:!1},permissions:function(){return f?{supported:!1,getAll:function(b){b&&b({permissions:[]})},request:function(b,a){a&&a(!1)},remove:function(b,a){a&&a(!0)}}:{}}(),i18n:{native_support:!1,getMessage:function(){},getUILanguage:function(){return navigator.language},getAcceptLanguages:function(b){b([])}},
idle:function(){if(f)return{queryState:function(b,a){}}}(),other:function(){if(f){var b={openDatabase:function(a,b,d,g){var e=window.openDatabase;if(e)return e(a,b,d,g)},requestFileSystem:function(a,b,d,e){var f=window.requestFileSystem||window.webkitRequestFileSystem;if(f)return f(a,b,d,e);e("not supported")}};b.__defineGetter__("webkitNotifications",function(){return window.webkitNotifications});return b}}()});var h=window.close,l=window.location.href,p=0!=l.search(e.extension.getURL("options.html"))&&
0!=l.search(e.extension.getURL("action.html"));window.close=function(){safari.self&&!p?safari.self.hide():h()};safari.extension.globalPage&&safari.extension.globalPage.contentWindow===window||e.internal.listeners.register("internal.close",function(b){h()});(function(){var b=e.FEATURES,a=null;try{e.extension.inIncognitoContext||(b.HTML5.LOCALSTORAGE=a=window.localStorage)}catch(c){console.warn("prep: window.localStorage will be unavailable")}b.HTML5.LOCALSTORAGE||(b.HTML5.LOCALSTORAGE=function(b){var d=
{};return{setItem:function(a,b){d[a]=b},getItem:function(b,c){var e;return d.hasOwnProperty(b)?d[b]:a&&void 0!==(e=a.getItem(b))?e:c},removeItem:function(a){d[a]=void 0}}}(window.usable_local_storage));b.DB.USE=b.DB.DEFAULT;try{b.HTML5.LOCALSTORAGE&&(b.DB.NO_WARNING="nowarning"===b.HTML5.LOCALSTORAGE.getItem("#brokenprofile"),b.DB.USE=b.HTML5.LOCALSTORAGE.getItem(b.CONSTANTS.STORAGE.TYPE)||b.DB.DEFAULT)}catch(c){console.warn("prep: error at storage type detection",c)}b.RUNTIME.ALLOWS_FILE_SCHEME_ACCESS=
!1;b.INITIALIZED=!0})()})(window.rea);
