(function(h){var e=h.safari=h.safari||h.top.safari||{self:{tab:{dispatchMessage:function(){}}},extension:{globalPage:{},baseURI:""}},c=h.rea={globals:window,extend:function(b){var a=function(d,b){for(var f in d)if(d.hasOwnProperty(f))if(Object.getOwnPropertyDescriptor(d,f).get)b.__defineGetter__(f,d.__lookupGetter__(f));else{var c=d[f],e=typeof c;"undefined"!=e&&(null===c?b[f]=c:"object"==e?(b[f]=b[f]||{},a(c,b[f])):"array"==e?(b[f]=b[f]||[],a(c,b[f])):b[f]=c)}};a(b,c)},internal:{new_uuid:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(b){var a=16*Math.random()|0;return("x"==b?a:a&3|8).toString(16)})},info:{read:function(b,a){if(!c.internal.info.content)try{var d=new window.XMLHttpRequest;d.open("GET",e.extension.baseURI+"Info.plist",!1);d.send(null);c.internal.info.content=d.responseText}catch(g){}return c.internal.info.content?(c.internal.info.content.match(new RegExp("<key>"+b+"</key>[ \\t\\n\\r]*<"+a+">([^<]*)</"+a+">"))||[])[1]:null}},eventing:{dispatchMessage:function(b,a){e.self.tab?e.self.tab.dispatchMessage(b,
a):e.extension&&e.extension.globalPage.contentWindow&&e.extension.globalPage.contentWindow.rea.internal.listeners.run(b,{message:a,target:{page:{dispatchMessage:function(a,b){c.internal.listeners.run(a,{message:b})}},url:window.location.href}})}},responses:function(){var b={};return{register:function(a,d){var g=d||c.internal.new_uuid();b[g]=a;return g},run:function(a,d,c,f){b[a]&&(b[a](d,c),f||delete b[a])},delete:function(a){delete b[a]}}}(),listeners:function(){var b={};(e.application||e.self).addEventListener("message",
function(a){var d=b[a.name];d&&d.length&&d.forEach(function(b){b(a)})},!1);return{register:function(a,d){b[a]=b[a]||[];b[a].push(d)},run:function(a,d){b[a]&&b[a].forEach(function(a){a(d)})}}}()}};c.extend({page:{reload:function(){e.self.width=Math.max(1,e.self.width-20);window.location.reload()}},runtime:function(){var b={};b.__defineGetter__("lastError",function(){return""});b.__defineGetter__("id",function(){return(e.extension.baseURI.match(/[^:]+:\/\/[^-]+-([^\/]+)/)||[])[1]||"SafariTM"});b.__defineGetter__("short_id",
function(){return b.id.replace(/[^0-9a-zA-Z]/g,"").substr(0,4)});return b}(),extension:function(){var b=[];c.internal.listeners.register("onMessage",function(a){var d=c.internal&&c.internal.tabs?(c.internal.tabs.getByPage(a.target.page)||c.internal.tabs.register(a.target.page)).id:null;b.forEach(function(b){b(a.message.data,{tab:{page:a.target.page,url:a.target.url||"",id:d},url:a.target.url||""},function(b){b={response_id:a.message.response_id,data:b};var d=a.target.page||a.target.tab;d&&d.dispatchMessage("onMessage.response",
b)})})});c.internal.listeners.register("onMessage.response",function(a){c.internal.responses.run(a.message.response_id,a.message.data)});c.internal.listeners.register("connect.postMessage",function(a){c.internal.responses.run(a.message.response_id,a.message.data,a.message.sender||a.target,!0)});return{onMessage:{addListener:function(a){b.push(a)}},getURL:function(a){return e.extension.baseURI+(a||"").replace(/^\//,"")},sendMessage:function(a,b){var e={response_id:c.internal.responses.register(b),
data:a};c.internal.eventing.dispatchMessage("onMessage",e)},connect:function(a){var b=[],g=[],f={postMessage:function(a){e.self.tab.dispatchMessage("connect.postMessage",{response_id:k,data:a||{},sender:{url:window.location.href}})},onMessage:{addListener:function(a){b.push(a)}},onDisconnect:{addListener:function(a){g.push(a)}},disconnect:function(){e.self.tab.dispatchMessage("connect.postMessage",{response_id:k});f=g=b=null}},k=c.internal.responses.register(function(a,e){f&&(a?b.forEach(function(b){b(a)}):
(g.forEach(function(a){a()}),c.internal.responses.delete(k),f=null))});e.self.tab.dispatchMessage("connect",{response_id:k});return f}}}()});c.extend(function(){var b=20,a="537.33";try{a=parseInt(navigator.userAgent.match(/AppleWebKit\/([0-9]+\.[0-9]+)/)[1])}catch(c){}try{b=parseInt(navigator.userAgent.match(/Version\/([0-9]+)\./)[1])}catch(c){}var d={CONSTANTS:{STORAGE:{SCHEMA:"#schema",TYPE:"#storage",CONFIG:"#config",VERSION:"#version",LEGACY_VERSION:"TM_version",LAST_START:"#laststart",UPDATE:"#update",
BEGGING:"#begging"},PREFIX:{SCRIPT_UID:"@uid#",COND:"@re#",STORE:"@st#",SCRIPT:"@source#",EXTERNAL:"@ext#",META:"@meta#"}},RUNTIME:{BROWSER:"safari",SAFARI:!0,BROWSER_VERSION:b,WEBKIT_VERSION:a,FAST_EXEC_SUPPORT:!1,DETECT_CONSTRUCTORS_BY_KEYS:!0,ALLOWS_FILE_SCHEME_ACCESS:null,MAX_SCRIPTS:1E3,CAN_SAVEAS_ZIP:!1,INCOGNITO_MODE:!1},ACTIONMENU:{COLUMNS:3,CLOSE_ALLOWED:!0,MIN_DELAY:0},OPTIONPAGE:{CLOSE_ALLOWED:!1},DB:{USE:null,DEFAULT:"chromeStorage"},XMLHTTPREQUEST:{RETRIES:0,PARTIAL_SIZE:16777216,COOKIE_PASSTHROUGH:!0},
SCRIPT_DOWNLOAD:{TIMEOUT:15},PINGPONG:{RETRIES:10},MISC:{TIMEOUT:1,IDLE_TIMEOUT:30,DISTURBANCE_ALLOWED:60},HTML5:{LOCALSTORAGE:null},REQUESTS:{HAS_SENDER_ID:!1,INTERNAL_PAGE_PROTOCOL:"safari-extension:",GET_INTERNAL_PATH_REGEXP:function(a,b){var c=/(\/|\.|\+|\?|\||\(|\)|\[|\]|\{|\}|\\)/g;return new RegExp(e.extension.baseURI.replace(c,"\\$1")+"([a-zA-Z"+(a?"\\/":"")+"]*)"+(b||"").replace(c,"\\$1"))},GET_INTERNAL_PAGE_REGEXP:function(){return d.REQUESTS.GET_INTERNAL_PATH_REGEXP(!1,".html")}},OPTIONS:{HAS_CSP:!1,
NATIVE_SCRIPT_IMPORT:!1,CAN_DOWNLOAD:!1}};return{FEATURES:d}}())})(window);
