Registry.require(["crcrc","helper","layout/default/htmlutil","i18n","layout/default/layout_helper"],function(){var t=rea.FEATURES,r=Registry.get("crcrc").cr,h=Registry.get("crcrc").crc,x=Registry.get("helper"),u=Registry.get("layout/default/htmlutil"),k=Registry.get("i18n"),y=Registry.get("layout"),z=Registry.get("layout/default/layout_helper"),v=z.images;y.render(function(){var p={};z.addStyle();var J=function(b,a){var d=[];if(a.sub_menu_item){if(a.items.length){var c=h("table","actiontable","actiontable-"+
a.name);A(c,a.items);d.push(c)}}else if(c=null,a.image?c=u.createImage(v.get(a.image),a.name,a.id,null,""):a.enabler&&(c=u.createImage(rea.extension.getURL(p.enabled?"/layout/default/images/button_ok.png":"/layout/default/images/cancel.png"),a.name,a.uuid,null,"")),c&&d.push(c),a.url||a.urls){for(var c=r("span",a.name,a.id,"urls"),f=a.urls||[a],e=0;e<f.length;e++){var g=f[e],q=document.createElement("span");q.textContent=g.name;var w=a.urls?q:b;w.url=g.url;w.newtab=g.newtab;$(w).addClass("clickable").on("click auxclick",
function(a){B(this.url,this.newtab);a.preventDefault()});c.appendChild(q);e<f.length-1&&(g=document.createElement("span"),g.textContent=" | ",c.appendChild(g))}d.push(c)}else if(a.menucmd){var l=document.createElement("span");b.id=a.id;f=function(){E(this.id,function(){t.ACTIONMENU.CLOSE_ALLOWED&&window.close()})};b.addEventListener("click",f);$(b).addClass("clickable");l.textContent=a.name;a.accessKey&&(c=a.accessKey[0].toUpperCase(),F(c,f,b)?(f=new RegExp(c,"i"),e=l.textContent.search(f),g=[],-1==
e&&(l.textContent+=" ("+c+")",e=l.textContent.search(f)),g.push({text:l.textContent.substr(0,e)}),g.push({text:l.textContent.substr(e,1),class:"underlined"}),g.push({text:l.textContent.substr(e+1)}),l.textContent="",g.forEach(function(c){var b=h("span",c.class||"",a.id,c);b.textContent=c.text;l.appendChild(b)})):console.warn("Registering keyboard shortcut for '"+a.name+"' failed"));d.push(l)}else if(a.button)c=h("span",a.display||"",a.name,a.id,"bu",!0),c.textContent=a.name,b.key=a.id,b.warning=a.warning,
b.reload=a.reload,b.data=a.data,b.addEventListener("click",function(){var a=!0;this.warning&&(a=G(this.warning));a&&H(this.key,{reload:this.reload,data:this.data})}),$(b).addClass("clickable"),d.push(c);else if(a.userscript){var c=h("div","clickable",a.name,a.uuid,"ai"),n;if(a.uuid&&(e=null,e=a.blacklisted?"enabler_warning":a.enabled?a.contexter?"enabler_enabled enabler_later":"enabler_enabled":"enabler_disabled",g=a.blacklisted?k.getMessage("This_script_is_blacklisted_"):a.enabled?k.getMessage("Enabled"):
k.getMessage("Disabled"),f=function(a){if(a&&(0!=a.button||a.ctrlKey||a.metaKey))return B(rea.extension.getURL("options.html")+"#nav="+this.key,!0),a.stopPropagation(),a.preventDefault(),!1;I(this.uuid,"enabled",!this.oldvalue)},e=u.createEnabler(e,a.uuid,"enabled",{append:"enabled",disabled:a.blacklisted,title:g},f),e.oldvalue=a.enabled,d.push(e),e=r("div",a.name,a.uuid,"name"),e.textContent=k.getTranslation(a,"name"),c.appendChild(e),c.uuid=a.uuid,c.oldvalue=a.enabled,c.key=a.uuid,$(c).on("click auxclick",
f),a.blacklisted&&(b.setAttribute("title",k.getMessage("This_script_is_blacklisted_")),$(c).addClass("crossedout")),f=[],a.nnew||a.system||!a.origin||(e=h("div","action_issue",a.name,a.uuid,"action_issue"),q=u.createImage(v.get("flag"),"",a.uuid,"issue",k.getMessage("Report_an_issue_to_the_script_hoster_")),g=h("span","",a.name,a.uuid,"action_issue_expl"),g.textContent=k.getMessage("Report_an_issue_to_the_script_hoster_").split(/[\.\(]+/)[0],e.appendChild([q,g]),$(e).click(function(){C(a.uuid,"hoster")}),
f.push(e)),a.nnew||a.system||!a.support||(e=h("div","action_issue",a.name,a.uuid,"action_bug"),q=u.createImage(v.get("bug"),"",a.uuid,"bug",k.getMessage("Report_a_bug")),g=h("span","",a.name,a.uuid,"action_issue_expl"),g.textContent=k.getMessage("Report_a_bug"),e.appendChild([q,g]),$(e).click(function(){C(a.uuid,"author")}),f.push(e)),f.length)){n=h("div","actionenablercol",a.name,a.uuid,"actionenablercol");e=h("img","actionenabler clickable",a.name,a.uuid,"actionenabler");e.src=v.get("enabler");
$("body").click(function(){$(".action_issues").hide()});$(e).click(function(a){var c=$(n).find(".action_issues");$(c).is(":visible")||$(".action_issues").hide();c.toggle();a.stopPropagation()});var m=h("div","action_issues",a.name,a.uuid,"action_bug");f.forEach(function(a){m.appendChild(a)});m.setAttribute("style","display:none;");n.appendChild(m);n.appendChild(e)}d.push(c);n&&d.push(n)}else c=r("span",a.name,a.id,"ai"),c.textContent=a.name,d.push(c);return d},A=function(b,a,d){Object.keys(a).forEach(function(c){var f=
a[c];if(!b)if(d[f.pos])f.items&&f.items.length&&$(d[f.pos]).show();else{console.warn("Warn(cAm): unknown pos "+f.pos);return}var e=(c=b||d[f.pos])?r("tr",f.name,f.uuid||f.id,"outer"):null,g=J(e,f);if(g&&g.length){c.appendChild(e);var h;for(c=0;h=g[c];c++){var k=c==g.length-1?3-c:0,l=r("td","actiontd",f.name,f.uuid||f.id,c);0<k&&l.setAttribute("colspan",k);h&&l.appendChild(h);e.appendChild(l)}}})},D=function(b,a){var d=$("#action"),c=r("div");c.setAttribute("id","action");d.replaceWith(c);var f=h("table",
"actionlayout","actionlayout");c.appendChild(f);c=h("tr","actionpostr","hor");d=h("td","actionpostd","hor_west");c.appendChild(d);f.appendChild(c);var e=h("table","actionregion","top"),g=h("table","actionregion","right"),k,m=h("table","actionregion","left"),l=h("table","actionregion","bottom");if(2<Math.min(p.action_menu_columns,t.ACTIONMENU.COLUMNS)){k=h("table","actionregion","center");var n=h("td","actionpostd","hor_center"),f=h("td","actionpostd","hor_east");n.appendChild(k);c.appendChild(n);
c.appendChild(f)}else 1<Math.min(p.action_menu_columns,t.ACTIONMENU.COLUMNS)?(k=g,f=h("td","actionpostd","hor_east"),c.appendChild(f)):k=f=m;$([k,g]).hide();d.appendChild(e);f.appendChild(g);d.appendChild(m);d.appendChild(l);A(null,b,{top:e,left:m,center:k,right:g,bottom:l})},B=function(b,a){try{var d=function(){a&&t.ACTIONMENU.CLOSE_ALLOWED&&window.close()};a?sendMessage({method:"newTab",url:b},d):rea.tabs.getSelected(null,function(c){rea.tabs.sendMessage(c.id,{method:"loadUrl",url:b,newtab:a},d)})}catch(c){console.warn("lU:",
c)}},G=function(b){var a=confirm(b.msg),d={};a&&b.ok?d=b.ok:!a&&b.cancel&&(d=b.cancel);if(b.ok||b.cancel)a=!0;d.url&&sendMessage({method:"newTab",url:d.url},function(a){});return a},C=function(b,a,d){try{sendMessage({method:"reportAnIssue",uuid:b,to:a},function(a){d&&d()})}catch(c){console.warn("raI:",c)}},H=function(b,a){try{sendMessage({method:"buttonPress",name:b,data:a.data},function(b){a.reload&&rea.page.reload()})}catch(d){console.warn("rSU:",d)}},m={},K=function(b,a,d){document.body.addEventListener("keydown",
function(a){a.altKey||a.ctrlKey||a.shiftKey||Object.keys(m).forEach(function(b){(b=m[b])&&a.keyCode==b.key&&b.cb.apply(b.elem||window,[])})},!1)},F=function(b,a,d){b=b.charCodeAt(0);if(m[b])return console.log("MenuCmdKeyListener: ...failed!"),!1;m[b]={key:b,cb:a,elem:d};return!0},E=function(b,a){try{sendMessage({method:"execMenuCmd",id:b},function(b){a&&a()})}catch(d){console.warn("Error(eMC):",d)}},I=function(b,a,d){try{b={method:"modifyScriptOptions",uuid:b},a&&""!=a&&(b[a]=d),sendMessage(b,function(a){document.getElementById("action").innerHTML=
"";a&&(a.i18n&&k.setLocale(a.i18n),a.items&&(a.options&&(p=x.assign(p,a.options)),D(a.items)))})}catch(c){console.warn("Error(mSo): "+c.message)}};rea.extension.onMessage.addListener(function(b,a,d){"updateActions"==b.method?rea.page.reload():console.log("onMessage: Unknown method '"+b.method+"'")});(function(b,a,d){var c=Date.now();sendMessage({method:"loadTree",referrer:b,layout:!0},function(b){b.options&&(p=x.assign(p,b.options));b.layout&&y.applyTheme(b.layout);b.i18n&&k.setLocale(b.i18n);var e=
Date.now()-c,g=function(){a(b)};!d||e>=d?g():window.setTimeout(g,d-e)})})("actions",function(b){if(b.options&&b.options.layout_user_css){var a=document.createElement("style");a.innerHTML=b.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(a)}K();D(b.items)},t.ACTIONMENU.MIN_DELAY)})});
